# Shopify Environments config for Shoify CLI
# See: [Environments](https://shopify.dev/docs/themes/tools/cli/environments)
#
# NOTE: DO NOT store sensitive data in this file!
#       This includes [Theme Access Passwords](https://shopify.dev/docs/themes/tools/cli#authentication)!

[environments.prod]
store = "fab-development.myshopify.com"
path = "./dist"

[environments.dev]
store = ""
path = "./dist"
